### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by OybekKayumov** [fahdrahali/todolist#2]
Hey @fahdrahali 👋 Great job with your project 👍 Your project is looking great, Its design looks perfect 💯.
There are some things we would suggest you apply in your code

- [x]  We suggest you use method `forEach` instead of using `map`, when you use `map`, you will create `new `array.🌞

Happy coding!🚀

**Comment by fahdrahali** [comment]
thank you,
that is a best practice.
